repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.1.0
    hooks:
    - id: end-of-file-fixer
    - id: trailing-whitespace
  - repo: https://github.com/ambv/black
    rev: 19.10b0
    hooks:
      - id: black
        args: ['--line-length', '127']
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.2
    hooks:
      - id: flake8
        args: ['--max-line-length=127', '--ignore=W191,W201,W291,W293,W391,W503,W605,E101,E203,E262,E265,E266,E302,E402,E501,E711,E712,E713,E714,E721,E741,F401,F403,F405,F811,F841']
